1.CREATE DATABASE JTHCMS

2.CREATE TABLE `JTHCMS`.`PublishContent` 
( `Id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`Title` VARCHAR(100) NOT NULL , 
	`About` VARCHAR(400) NOT NULL , 
	`Category` VARCHAR(50) NOT NULL , 
	`PublishDate` DATETIME NOT NULL , 
	`HappenDate` DATETIME NOT NULL DEFAULT now(), 
	`Author` VARCHAR(50) NOT NULL , 
	`ThumbImg` VARCHAR(150) NOT NULL , 
	`MainEditor` TEXT NOT NULL , 
	`Weight` INT NOT NULL DEFAULT '0');

3.CREATE TABLE `JTHCMS`.`User` 
( `Id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`UserName` VARCHAR(100) NOT NULL , 
	`Pwd` VARCHAR(100) NOT NULL , 
	`Power` VARCHAR(4000) NOT NULL );

