1.CREATE DATABASE THW

2.CREATE TABLE `THW`.`member` ( `Id` BIGINT NOT NULL AUTO_INCREMENT , `UserName` VARCHAR(30) NOT NULL , `Pwd` VARCHAR(20) NOT NULL , `RoleId` INT NOT NULL DEFAULT '0' , PRIMARY KEY (`Id`), UNIQUE `UserName_U` (`UserName`(30))) ENGINE = MyISAM;